import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NavbarMain from '../components/navbar/navbar-main'
import FooterPage from '../components/footer/footer'
import ToastProvider from '@/provider/toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <NavbarMain />
        {children}
        <FooterPage />
      </body>
    </html>
  )
}
